config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  devise_scope :users do
    get '/users', to: redirect("/users/sign_up")
  end
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  #ゲスト用
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }


  namespace :admin do
    resources :users,  only: [:index, :show, :edit, :update] do
      get 'counseling_posts_index' => 'users#counseling_posts_index'
      get 'post_comments_index' => 'users#post_comments_index'
    end
    resources :counseling_posts,  only: [:index, :show, :destroy] do
      resources :post_comments, only: :destroy
    end
    resources :post_comments, only: [:index, :show]
  end

  scope module: :public do
    root :to => 'homes#top'
    resources :users, only: [:show, :edit, :update] do
      get    'withdraw_confirm'  =>  'users#withdraw_confirm'
      patch  'withdraw'          =>  'users#withdraw'
    end
    resources :counseling_posts do
      resource :favorites, only: [:create, :destroy]
      resource :votes, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy] do
        resource :good_comments, only: [:create, :destroy]
      end
    end
    get "ranking" => "users#ranking"
    resources :notifications, only: [:index, :destroy] do
      post :mark_read, on: :member
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  validates :comment, presence: true, length: { maximum: 500 }

  belongs_to :user
  belongs_to :counseling_post
  has_many :good_comments, dependent: :destroy
  has_many :notifications, dependent: :destroy

  scope :created_this_month, -> { where(created_at: Time.current.beginning_of_month..Time.current.end_of_day) }

  def good_commented_by?(user)
    good_comments.exists?(user_id: user.id)
  end

  #相談者からグッドアドバイス評価がもらえたときの通知
  def create_notification_by(current_user, id, user_id)
    return if current_user.id == user_id
    notification = current_user.active_notifications.new(
      post_comment_id: id,
      visited_id: user_id,
      action: "good_comment"
    )
    notification.checked = true if notification.visitor_id == notification.visited_id
    notification.save if notification.valid?
  end

end

app/controllers/admin/post_comments_controller.rb
class Admin::PostCommentsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @post_comments = PostComment.order(created_at: :desc).page(params[:page]).per(15)
  end

  def show
    @post_comment = PostComment.find(params[:id])
    @counseling_post = @post_comment.counseling_post
  end

  def destroy
    @post_comment = PostComment.find(params[:id])
    @post_comment.destroy
    @counseling_post = CounselingPost.find(params[:counseling_post_id])

    if params[:from_show_page] == 'true'
      # 詳細ページからのリクエストがあった場合
      flash[:post_comment] = '回答を削除しました'
      redirect_to admin_post_comments_path
    else
      # 一覧ページからのリクエストがあった場合
      flash.now[:post_comment] = '回答を削除しました'
      render :destroy
    end
  end
end

app/helpers/admin/post_comments_helper.rb
module Admin::PostCommentsHelper
end

app/views/admin/post_comments/_comment_list.html.erb
  <div class="row no-gutters">
    <% if post_comments.present? %>
      <div class="col-12" id="flash-message">
        <% if flash[:post_comment] %>
          <%= render "layouts/flash", message: flash[:post_comment] %>
        <% end %>
      </div>
      <table class="table">
        <tbody>
          <% post_comments.each do |post_comment| %>
            <tr id="post-comment-<%= post_comment.id %>">
              <td class="col-2">
                <%= link_to admin_user_path(post_comment.user.id) do %>
                  <div class="user-info">
                    <%= image_tag post_comment.user.get_profile_image, size: '50x50', class: "rounded-circle user-image" %>
                    <%= post_comment.user.name %>さん
                  </div>
                <% end %>
              </td>
              <td style="word-wrap: break-word; word-break: break-all; overflow-wrap: break-word;">
                <%= simple_format(post_comment.comment) %>
              </td>
              <td class="col-2">
                <%= link_to "詳細", admin_post_comment_path(post_comment.id), class: "btn btn-color btn-sm ml-1" %>
                <%= link_to "削除", admin_counseling_post_post_comment_path(post_comment.counseling_post, post_comment), remote: true, class: "btn btn-delete btn-sm ml-1", method: :delete %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <p class="col-12 text-center">コメントが存在しません。</p>
    <% end %>
  </div>

app/views/admin/post_comments/_index.html.erb
<h3 class="mb-4">
  <strong>回答（<%= counseling_post.post_comments.count %>件）</strong>
</h3>

<% counseling_post.post_comments.each do |post_comment| %>
  <div class="mb-2">
    <div class="comment-card-body d-flex">
      <div class="d-flex flex-column align-items-start mt-2">
        <div style="width: 100px;">
          <%= link_to admin_user_path(post_comment.user_id) do %>
            <%= image_tag post_comment.user.get_profile_image, size: '50x50', class: "rounded-circle mr-3 user-image" %>
          <% end %>
          <div>
            <%= link_to admin_user_path(post_comment.user_id),class: "user-link" do %>
              <p class="card-title mb-0"><%= post_comment.user.name %>さん</p>
            <% end %>
          </div>
        </div>
      </div>
      <div class="container">
        <div class="answer-comment d-flex flex-column justify-content-between">
          <p class="card-text mb-0"><small><%= time_ago_in_words(post_comment.created_at) %>前</small></p>
          <p class="card-text" style="word-wrap: break-word; word-break: break-all;">
            <%= post_comment.comment %>
          </p>
          <% if current_admin %>
            <div class="mt-auto d-flex justify-content-end mb-1">
              <%= link_to "削除", admin_counseling_post_post_comment_path(post_comment.counseling_post, post_comment), remote: true, class: "btn btn-delete", method: :delete %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/post_comments/destroy.js.erb
$('.post-comments-index').html("<%= j(render "admin/post_comments/index", counseling_post: @counseling_post,post_comment: @post_comment) %>")
$('#flash-message').html("<%= j(render "layouts/flash") %>").show().delay(10000).fadeOut();
$('#post-comment-<%= @post_comment.id %>').remove();

app/views/admin/post_comments/destroy_index.js.erb
$('.post-comments-index').html("<%= j(render "admin/post_comments/index", counseling_post: @counseling_post,post_comment: @post_comment) %>")
$('#flash-message').html("<%= j(render "layouts/flash") %>").show().delay(10000).fadeOut();
$('#post-comment-<%= @post_comment.id %>').remove();

app/views/admin/post_comments/index.html.erb
<div class="py-4" style=" background-color: #19A7CE;">
  <h2 class="text-center" style="color: #FFF; font-weight: bold;">回答一覧</h2>
  <span style="display: block; text-align: center; font-size: 20px;">Comments</span>
</div>

<div class="container mt-5">
  <div class="row no-gutters">
    <% if @post_comments.present? %>
      <div class="col-12" id="flash-message">
        <% if flash[:post_comment_created] %>
          <%= render "layouts/flash", message: flash[:post_comment_created] %>
        <% end %>
      </div>
      <table class="table">
        <tbody>
          <% @post_comments.each do |post_comment| %>
            <tr id="post-comment-<%= post_comment.id %>">
              <td class="col-2">
                <%= link_to admin_user_path(post_comment.user.id) do %>
                  <div class="user-info">
                    <%= image_tag post_comment.user.get_profile_image, size: '50x50', class: "rounded-circle user-image" %>
                    <%= post_comment.user.name %>さん
                  </div>
                <% end %>
              </td>
              <td style="word-wrap: break-word; word-break: break-all; overflow-wrap: break-word;">
                <%= simple_format(post_comment.comment) %>
              </td>
              <td class="col-2">
                <%= link_to "詳細", admin_post_comment_path(post_comment.id), class: "btn btn-color btn-sm ml-1" %>
                <%= link_to "削除", admin_counseling_post_post_comment_path(post_comment.counseling_post, post_comment), remote: true, class: "btn btn-delete btn-sm ml-1", method: :delete %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <p class="col-12 text-center">コメントが存在しません。</p>
    <% end %>
  </div>
  <%= paginate @post_comments %>
</div>

app/views/admin/post_comments/show.html.erb
<div class="py-4" style=" background-color: #19A7CE;">
  <h2 class="text-center" style="color: #FFF; font-weight: bold;">回答の詳細</h2>
  <span style="display: block; text-align: center; font-size: 20px;">Comment</span>
</div>

<div class="container mt-5">

  <!--コメントの表示-->
  <div class="row mt-5 no-gutters">
    <h4>回答</h4>
    <table class="table" style="background-color: #f8f8f8; border-radius: 10px; border: 3px solid #EBEBEB;">
      <tbody>
        <tr id="post-comment-<%= @post_comment.id %>">
          <td class="col-2">
            <%= link_to admin_user_path(@post_comment.user.id) do %>
              <div class="user-info">
                <%= image_tag @post_comment.user.get_profile_image, size: '50x50', class: "rounded-circle user-image" %>
                <%= @post_comment.user.name %>さん
              </div>
            <% end %>
          </td>
          <td class="col-8" style="word-wrap: break-word; word-break: break-all; overflow-wrap: break-word;">
            <%= simple_format(@post_comment.comment) %>
          </td>
          <td class="col-1">
            <%= link_to "削除", admin_counseling_post_post_comment_path(@post_comment.counseling_post, @post_comment, from_show_page: true), class: "btn btn-delete btn-sm", method: :delete %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>


  <div class="row mt-5">

    <!-- CounselingPostの詳細（左側） -->
    <div class="col-md-6">
      <%= image_tag @counseling_post.get_image, class: "img-fluid", style: "border-radius: 10px; box-shadow: 0 0 8px rgba(0, 0, 0, .16);" %>
      <div class="d-flex justify-content-between mt-2">
        <div>
          質問日時：<%= @counseling_post.created_at.strftime("%Y年%m月%d日") %>
          <div class="d-flex align-items-end user-link mt-3">
            <%= link_to admin_user_path(@counseling_post.user_id), class: "user-link" do %>
              <%= image_tag @counseling_post.user.get_profile_image, size: '80x80', class: "rounded-circle user-image" %>
            <% end %>
            <%= link_to admin_user_path(@counseling_post.user_id), class: "ml-1 mb-0" do %>
              <%= @counseling_post.user.name %>さん
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <!-- CounselingPostの詳細（右側） -->
    <div class="col-md-6">
      <div class="card-border p-3">
        <h4 class="border-bottom border-dark" style="white-space: pre-wrap; overflow-wrap: break-word;"><strong><%= @counseling_post.title %></strong></h4>
        <p style="white-space: pre-wrap; overflow-wrap: break-word;"><%= @counseling_post.content %></p>
        <div class="d-flex align-items-center mt-5">
          <% if @counseling_post.star.present? %>
            <div class="mr-2">お気に入り度：</div>
            <%= render "admin/counseling_posts/star", counseling_post: @counseling_post %>
          <% end %>
        </div>
        <% if @counseling_post.usage_frequency.present? %>
          <p>使用頻度： <%= @counseling_post.usage_frequency_i18n %></p>
        <% end %>
        <% if @counseling_post.tags.present? %>
          <% @counseling_post.tags.each do |tag| %>
            <%= link_to admin_counseling_posts_path(tag_ids: tag.id), class: "tag-link btn-sm mb-1" do %>
              <span><i class="fa-solid fa-hashtag"></i><strong><%=tag.name%></strong></span>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>