config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  devise_scope :users do
    get '/users', to: redirect("/users/sign_up")
  end
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  #ゲスト用
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }


  namespace :admin do
    resources :users,  only: [:index, :show, :edit, :update] do
      get 'counseling_posts_index' => 'users#counseling_posts_index'
      get 'post_comments_index' => 'users#post_comments_index'
    end
    resources :counseling_posts,  only: [:index, :show, :destroy] do
      resources :post_comments, only: :destroy
    end
    resources :post_comments, only: [:index, :show]
  end

  scope module: :public do
    root :to => 'homes#top'
    resources :users, only: [:show, :edit, :update] do
      get    'withdraw_confirm'  =>  'users#withdraw_confirm'
      patch  'withdraw'          =>  'users#withdraw'
    end
    resources :counseling_posts do
      resource :favorites, only: [:create, :destroy]
      resource :votes, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy] do
        resource :good_comments, only: [:create, :destroy]
      end
    end
    get "ranking" => "users#ranking"
    resources :notifications, only: [:index, :destroy] do
      post :mark_read, on: :member
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :name, presence:true, length: { maximum: 15 }
  validates :introduction, length: { maximum: 50 }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :counseling_posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :counseling_post_favoirtes, through: :favorites, source: :counseling_post
  has_many :good_comments, dependent: :destroy
  has_many :good_comments_through_post_comments, through: :post_comments, source: :good_comments
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  ## ユーザーのgood_commentsの数（グッドアドバイス数）を取得。
  def total_good_comments_count
    good_comments_through_post_comments.count
  end

  #ランキングで表示するトータル数を取得。
  def good_comments_count
    good_comments_through_post_comments.created_this_month.count
  end

  def post_commennts_count
    post_comments.created_this_month.count
  end

  def votes_count
    votes.created_this_month.count
  end

  def total_count
    good_comments_count +  post_commennts_count + votes_count
  end

  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/user.png')
      profile_image.attach(io: File.open(file_path), filename: 'default-user-image.png', content_type: 'image/jpeg')
    end
    profile_image
  end

  #ゲストログイン機能としてゲストユーザーを作成する
  def self.guest
    find_or_create_by!(name: 'ゲストユーザー' ,email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.page(params[:page]).per(15)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "会員情報を編集しました。"
      redirect_to admin_user_path(@user)
    else
      render :edit
    end
  end

  def counseling_posts_index
    @user = User.find(params[:user_id])
    @counseling_posts = @user.counseling_posts.order(created_at: :desc).page(params[:page]).per(9)
  end

  def post_comments_index
    @user = User.find(params[:user_id])
    @post_comments = @user.post_comments.order(created_at: :desc).page(params[:page]).per(15)
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :email, :is_deleted, :admin)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/counseling_posts_index.html.erb
<div class="py-4" style=" background-color: #19A7CE;">
  <h2 class="text-center" style="color: #FFF; font-weight: bold;"><%= @user.name %>さんの相談投稿</h2>
  <span style="display: block; text-align: center; font-size: 20px;">Q&A</span>
</div>

<div class="container mt-5">
  <div class="row no-gutters post-list mt-2">
    <% if @counseling_posts.present? %>
      <%= render "admin/counseling_posts/index", counseling_posts: @counseling_posts %>
    <% else %>
      <div class="col-12">
        <p class="text-center">まだ投稿はありません。</p>
      </div>
    <% end %>
  </div>
  <%= paginate @counseling_posts %>
  <%= link_to "戻る", admin_user_path(@user), class: "text-center d-block mt-5" %>
</div>

app/views/admin/users/edit.html.erb
<div class="py-4" style=" background-color: #19A7CE;">
  <h2 class="text-center" style="color: #FFF; font-weight: bold;">登録情報編集</h2>
  <span style="display: block; text-align: center; font-size: 20px;">Edit</span>
</div>

<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-sm-8 col-12 mt-2 px-0">
      <%= render 'layouts/error', obj: @user %>
      <h4 class="mt-4"><%= @user.name %>さんの登録情報編集</h4>
    </div>
    <div class="col-sm-8 col-12 mt-3 mb-5 p-3" style="background-color: #f8f8f8; border-radius: 10px; border: 1px solid #EBEBEB;">
      <%= form_with model: @user, url: admin_user_path(@user), method: :patch do |f| %>
        <div class="form-group">
          <table class="table table-borderless">
            <tbody>
              <tr>
                <td>会員ID</td>
                <td><%= @user.id %></td>
              </tr>
              <tr>
                <td><%= f.label :name, "名前" %></td>
                <td><%= f.text_field :name, class: "form-control" %></td>
              </tr>
              <tr>
                <td><%= f.label :email, "メールアドレス" %></td>
                <td><%= f.email_field :email, class: "form-control" %></td>
              </tr>
              <tr>
                <td><%= f.label :introduction, "自己紹介" %></td>
                <td><%= f.text_area :introduction, class: "form-control" %></td>
              </tr>
              <tr>
                <td>会員ステータス</td>
                <td>
                  <%= f.radio_button :is_deleted, false, id: "is_deleted_false" %>
                  <%= f.label :is_deleted_false, "有効" %>
                  <%= f.radio_button :is_deleted, true, id: "is_deleted_true" %>
                  <%= f.label :is_deleted_true, "退会" %>
                </td>
              </tr>
              <tr>
                <td></td>
                <td><%= f.submit "変更を保存", class: "btn btn-submit" %></td>
              </tr>
            </tbody>
          </table>
        </div>
      <% end %>
    </div>
  </div>
  <div class="col-12 text-center">
    <%= link_to "戻る", admin_user_path(@user) %>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="py-4" style=" background-color: #19A7CE;">
  <h2 class="text-center" style="color: #FFF; font-weight: bold;">会員一覧</h2>
  <span style="display: block; text-align: center; font-size: 20px;">Users</span>
</div>

<div class="container mt-5">
  <div class="row">
    <table class="table">
      <thead>
        <tr>
          <th>会員ID</th>
          <th>ユーザー名</th>
          <th>メールアドレス</th>
          <th>会員ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.id %></td>
            <td>
              <%= link_to admin_user_path(user.id) do %>
                <div class="user-info">
                  <%= image_tag user.get_profile_image, size: '50x50', class: "rounded-circle user-image" %>
                  <%= user.name %>
                </div>
              <% end %>
            </td>
            <td><%= user.email %></td>
            <% if user.is_deleted == false %>
              <td class="text-success font-weight-bold">有効</td>
            <% else %>
              <td class="text-secondary font-weight-bold">退会</td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <%= paginate @users %>
</div>

app/views/admin/users/post_comments_index.html.erb
<div class="py-4" style=" background-color: #19A7CE;">
  <h2 class="text-center" style="color: #FFF; font-weight: bold;"><%= @user.name %>さんの回答一覧</h2>
  <span style="display: block; text-align: center; font-size: 20px;">Comments</span>
</div>

<div class="container mt-5">
  <%= render "admin/post_comments/comment_list", post_comments: @post_comments %>
  <%= paginate @post_comments %>
  <%= link_to "戻る", admin_user_path(@user), class: "text-center d-block mt-5" %>
</div>

app/views/admin/users/show.html.erb
<div class="py-4" style=" background-color: #19A7CE;">
  <h2 class="text-center" style="color: #FFF; font-weight: bold;">会員情報詳細</h2>
  <span style="display: block; text-align: center; font-size: 20px;">User</span>
</div>

<%= render "layouts/flash" %>
<div class="container mt-5">
  <div class="row mb-2 justify-content-between align-items-end no-gutters">
    <h4><%= @user.name %>さんの会員情報</h4>
    <div>
      <%= link_to admin_user_counseling_posts_index_path(@user), class: "btn btn-color btn-sm" do %>
        相談投稿一覧
      <% end %>
      <%= link_to admin_user_post_comments_index_path(@user), class: "btn btn-color btn-sm" do %>
        回答一覧
      <% end %>
    </div>
  </div>

  <div class="row no-gutters">
    <table class="table table-bordered">
      <tbody>
        <tr>
          <td class="col-sm-2 col-4">会員ID</td>
          <td><%= @user.id %></td>
        </tr>
        <tr>
          <td class="col-sm-2 col-4"></td>
          <td><%= image_tag @user.get_profile_image, size: '80x80', class: "rounded-circle user-image" %></td>
        </tr>
        <tr>
          <td class="col-sm-2 col-4">ユーザー名</td>
          <td><%= @user.name %></td>
        </tr>
        <tr>
          <td class="col-sm-2 col-4">メールアドレス</td>
          <td><%= @user.email %></td>
        </tr>
        <tr>
          <td class="col-sm-2 col-4">自己紹介</td>
          <td><%= @user.introduction %></td>
        </tr>
        <tr>
          <td class="col-sm-2 col-4">会員ステータス</td>
          <% if @user.is_deleted == false %>
            <td class="text-success font-weight-bold">有効</td>
          <% else %>
            <td class="text-secondary font-weight-bold">退会</td>
          <% end %>
        </tr>
        <tr>
          <td></td>
          <td>
            <%= link_to "編集する", edit_admin_user_path(@user.id), class: "btn btn-color btn-sm" %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="text-center mt-5"><%= link_to "会員一覧に戻る", admin_users_path %></div>
</div>