config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  devise_scope :users do
    get '/users', to: redirect("/users/sign_up")
  end
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  #ゲスト用
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }


  namespace :admin do
    resources :users,  only: [:index, :show, :edit, :update] do
      get 'counseling_posts_index' => 'users#counseling_posts_index'
      get 'post_comments_index' => 'users#post_comments_index'
    end
    resources :counseling_posts,  only: [:index, :show, :destroy] do
      resources :post_comments, only: :destroy
    end
    resources :post_comments, only: [:index, :show]
  end

  scope module: :public do
    root :to => 'homes#top'
    resources :users, only: [:show, :edit, :update] do
      get    'withdraw_confirm'  =>  'users#withdraw_confirm'
      patch  'withdraw'          =>  'users#withdraw'
    end
    resources :counseling_posts do
      resource :favorites, only: [:create, :destroy]
      resource :votes, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy] do
        resource :good_comments, only: [:create, :destroy]
      end
    end
    get "ranking" => "users#ranking"
    resources :notifications, only: [:index, :destroy] do
      post :mark_read, on: :member
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_error.html.erb
<% if obj.errors.any? %>
  <div class="error-messages">
    <h4><strong><i class="fa-solid fa-triangle-exclamation"></i><%= obj.errors.count %>件のエラーが発生しました</strong></h4>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-12">
      <% if flash[:notice] %>
        <div class="alert alert-success">
          <i class="fa-solid fa-check"></i><%= flash[:notice] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-danger">
          <i class="fa-solid fa-triangle-exclamation"></i><%= flash[:alert] %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<!-- コメント投稿成功時のフラッシュメッセージを表示 -->
<% if flash[:post_comment] %>
  <div class="alert alert-success">
    <%= flash[:post_comment] %>
  </div>
<% end %>

app/views/layouts/_flash_logout.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success mb-0">
    <%= flash[:notice] %>
  </div>
<% elsif flash[:alert] %>
  <div class="alert alert-danger mb-0">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container-fluid bg-dark mt-5">
    <div class="row">
      <div class="mx-auto">
        <div class="text-center mt-4">
          <a href="#" class="footer-link text-white mr-3">利用規約</a>
          <a href="#" class="footer-link text-white mr-3">プライバシーポリシー</a>
          <a href="#" class="footer-link text-white">お問い合わせ</a>
        </div>
        <p class="text-center footer-text text-white mt-3">&copy; 2023 Danshari. All rights reserved.</p>
        <p class="text-center footer-text" style="color: white;">
          <%= link_to "管理者ログイン", new_admin_session_path, style: "color: white;" %>
        </p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg header-bg-color">
    <div class="container">
      <%= link_to (current_admin ? admin_counseling_posts_path : root_path) do %>
        <%= image_tag "logo.png", alt: "ロゴ", class: "img-fluid logo" %>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="custom-toggler-icon"><i class="fas fa-bars"></i></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
        <ul class="navbar-nav align-items-center">
          <% if admin_signed_in? %>
            <li class="nav-item">
              <%= link_to 'お悩み相談', admin_counseling_posts_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to '回答一覧', admin_post_comments_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to '会員情報', admin_users_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link' %>
            </li>
          <% elsif user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'お悩み相談', counseling_posts_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "ランキング一覧", ranking_path, class: 'nav-link' %>
            </li>
            <li class="nav-item position-relative">
              <% if current_user.passive_notifications.where(checked: false).present? %>
                <span class="position-absolute top-0 translate-middle badge badge-pill badge-primary ml-5"><%= current_user.passive_notifications.where(checked: false).count %></span>
              <% end %>
              <%= link_to "通知", notifications_path, class: 'nav-link mr-5' %>
            </li>
            <li class="nav-item">
              <%= link_to "相談・質問をする", new_counseling_post_path, class: 'btn btn-color-blue text-white' %>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
                <%= image_tag current_user.get_profile_image, size: '50x50', class: "rounded-circle user-image mr-3" %>
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><%= link_to 'マイページ', user_path(current_user), class: 'dropdown-item' %></li>
                <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'dropdown-item' %></li>
              </ul>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "新規登録", new_user_registration_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_user_session_path, class: 'nav-link' %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Danshari</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/e01d44fda2.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
    <span id="back">
      <a href="#">
        <%= image_tag "topbtn.png", alt: "" %>
      </a>
    </span>
    <%= render "layouts/footer" %>
  </body>
</html>